config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations } do
  end
  root to: 'jobs#index'
  resources :jobs, only: [:index, :show] do
    resources :applications, only: :create, controller: :job_applications
    resources :rejections, only: :create, controller: :job_rejections
    resources :likes, only: :create
  end
  resources :applications, only: [:show, :index], controller: :job_applications
  get '/authorise', to: 'pages#authorise'
  get '/credentials', to: 'pages#credentials'
  get '/privacy-policy', to: 'pages#privacy'
  get '/support', to: 'pages#support'
  post '/report', to: 'pages#report'
  get '/likes', to: 'jobs#liked_jobs'
  namespace :admin do
    resources :candidates, only: [:index]
    resources :applications, only: [:index], controller: :job_applications
    resources :jobs, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_admin_navbar.html.erb
<div class="admin-navbar">
  <div class="admin-navbar-left">
    <%= image_tag "Swan.png", class: "admin-navbar-swan" %>
  </div>
  <div class="admin-navbar-right">
    <%= link_to "Users", admin_candidates_path, class: "admin-navbar-link grey medium-text"  %>
    <%= link_to "Applications", admin_applications_path, class: "admin-navbar-link grey medium-text" %>
    <%= link_to "Jobs", admin_jobs_path, class: "admin-navbar-link grey medium-text"  %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-silver-swan">
  <%= link_to "#", class: "filter-link" do %>
    <%= image_tag "filters.png" %>
  <% end %>
  <%= link_to root_path, class: "swan-link" do %>
    <%= image_tag "Swan.png" %>
  <% end %>
  <div class="dropdown">
    <%= image_tag "burger.png", id:"dropdownMenuTrigger" %>
    <ul id="dropdown-menu" class="navbar-dropdown" >
      <li class="dropdown-option">
        <a class="grey" href="#">My Jobs</a>
      </li>
      <div class="navbar-dropdown-divider"></div>
      <li class="dropdown-option">
        <%= link_to 'My Profile', edit_user_registration_path, class: 'grey' %>
      </li>
      <div class="navbar-dropdown-divider"></div>
      <li class="dropdown-option">
        <%= link_to 'Support', support_path, class: 'grey' %>
      </li>
      <div class="navbar-dropdown-divider"></div>
      <li class="dropdown-option">
        <%= link_to 'Privacy Policy', privacy_policy_path, class: 'grey' %>
      </li>
      <div class="navbar-dropdown-divider"></div>
      <% if current_user %>
        <li class="dropdown-option">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'grey' %>
        </li>
      <% else %>
        <li class="dropdown-option">
          <%= link_to 'Login', new_user_session_path, class: 'grey' %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<script>
  var dropdownTrigger = document.getElementById('dropdownMenuTrigger')
  var dropdownMenu = document.getElementById('dropdown-menu')
  dropdownTrigger.addEventListener('click', function() {
    dropdownMenu.classList.toggle('show')
  })
</script>