config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations } do
  end
  root to: 'jobs#index'
  resources :jobs, only: [:index, :show] do
    resources :applications, only: :create, controller: :job_applications
    resources :rejections, only: :create, controller: :job_rejections
    resources :likes, only: :create
  end
  resources :applications, only: [:show, :index], controller: :job_applications
  get '/authorise', to: 'pages#authorise'
  get '/credentials', to: 'pages#credentials'
  get '/privacy-policy', to: 'pages#privacy'
  get '/support', to: 'pages#support'
  post '/report', to: 'pages#report'
  get '/likes', to: 'jobs#liked_jobs'
  namespace :admin do
    resources :candidates, only: [:index]
    resources :applications, only: [:index], controller: :job_applications
    resources :jobs, only: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<div id="test-react"></div>
<!-- <div id="home-react"></div> -->

app/views/pages/support.html.erb
<div class="support-container">
  <div class="support-logo-holder">
    <div class="support-logo">
      <%= image_tag "Swan.png", class: "small-swan" %>
      <h1 class="text-center grey support-title">Support</h1>
    </div>
  </div>
  <div class="support-content">
    <p class="grey small-text text-center">Follow us on social</p>
    <div class="social-links-flex">
      <a href="https://www.facebook.com/SilverSwanRecruitment" target='blank'>
        <i class="fab fa-facebook-f maroon xl-text"></i>
      </a>
      <a href="https://twitter.com/silverswanjobs" target='blank'>
        <i class="fab fa-twitter maroon xl-text"></i>
      </a>
      <a href="https://www.instagram.com/silverswanrecruitment/" target='blank'>
        <i class="fab fa-instagram maroon xl-text"></i>
      </a>
      <a href="https://www.linkedin.com/company/silver-swan-recruitment/" target='blank'>
        <i class="fab fa-linkedin-in maroon xl-text"></i>
      </a>
      <a href="https://www.pinterest.co.uk/silverswanrecruitment/" target='blank'>
        <i class="fab fa-pinterest-p maroon xl-text"></i>
      </a>
    </div>
    <p class="grey small-text text-center large-margin-top">If you have run into any issues while using Silver Swan Search then we would love to hear about them so that we can fix them ASAP</p>
    <%= simple_form_for :report, url: report_path do |f| %>
    <%= f.input :content,
                as: :text,
                placeholder: 'Your issue....',
                label: false,
                input_html: {
                  value: params[:report].present? ? params[:report][:content] : nil, class: "support-form"
                } %>
    <div class="silver-swan-button big-silver-swan-button">
      <input type="submit" name="commit" value="Report" data-disable-with="Report" class="white roboto small-text">
    </div>
    <% end %>

    <p class="grey small-text text-center large-margin-top">Or if you would like to get in contact with the developers. Please visit us at <br><a href="https://hoxton-digital.com" class="grey underline">hoxton-digital.com</a></p>
  </div>
</div>